lang: en

title: Your awesome title
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: ""
author: ""
url:  # the base hostname & protocol for your site, e.g. http://example.com
baseurl:  # the subpath of your site, e.g. /blog
permalink: pretty
environment: development
google-tracking-id: "" # Google Tracking ID and property number

navigation:
- title: About
  url: /about
- title: Contact
  url: /contact

collections:
  posts:
    output: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-autoprefixer
autoprefixer:
  browsers:
  - last 2 versions
autoprefixer:
  only_production: true
