lang: en

title: Your awesome title
description: >-
  Write an awesome description for your new site here.
keywords: ""
author: "Meir Roth"
url:  # the base hostname & protocol for your site, e.g. http://example.com
baseurl:  # the subpath of your site, e.g. /blog
permalink: pretty
environment: development
google-tracking-id: # Google Tracking ID and property number
seo: # seo meta tags  (https://favicon.io/)
  og:
    type: # The type of the website. default is 'website'
    image:   # An image URL which should represent your website.
  twitter:
    username:  # creator twitter username
    card: # default is 'summary'

navigation:
- title: About
  url: /about
- title: Contact
  url: /contact

collections:
  posts:
    output: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-autoprefixer
autoprefixer:
  browsers:
  - last 2 versions
autoprefixer:
  only_production: true
